### ISSUE TITLE
some file are missing

### ISSUE THREAD

**Issue by framarini02** [realpaliy/Messenger#7]
"import Lottie" it gives me an error with no such module Lottie written
"import Firebase" it gives me an error with Couldn't build Objective-C module "firebase"
#import <FirebaseCore/FirebaseCore.h> this file are missing

**Comment by realpaliy** [comment]
Hey, try running `run pod install` in your terminal.

**Comment by framarini02** [comment]
Already done

**Comment by realpaliy** [comment]
Did it fix your issue?

**Comment by framarini02** [comment]
No

**Comment by realpaliy** [comment]
What version of Xcode do you have? Check out this StackOverflow question -- https://stackoverflow.com/questions/52077002/header-file-firebasecore-firebasecore-h-not-found-despite-importing-firebase

**Comment by framarini02** [comment]
Xcode 12

**Comment by realpaliy** [comment]
Oh, I see, do you use `mChat.xcodeproj` to run the app? You have to use the `mChat.xcworkspace` instead.

**Comment by framarini02** [comment]
i run mChat.xcodeproj

**Comment by realpaliy** [comment]
Yep, that is why some files are missing. You have to use  `mChat.xcworkspace` in order for this app to work. More information here about the difference between two here https://stackoverflow.com/questions/21631313/xcode-project-vs-xcode-workspace-differences

**Comment by framarini02** [comment]
so I have to start the file .xcworkspace first and press on run and then I have to use the other file .xcodeproj to start the app, right?

**Comment by realpaliy** [comment]
No, you now have to work only with `mChat.xcworkspace`. `mChat.xcodeproj ` file does not support CocoaPods, that is why some files were missing.

**Comment by framarini02** [comment]
ok. now I try

**Comment by framarini02** [comment]
one last thing. Why does the program always give me an error when trying to archive? The error comes from lottoe-ios and says Undefined symbol: type metadata for Swift._StringObject.Variant

**Comment by realpaliy** [comment]
It might be a problem with Xcode 12 since it is still in beta. I would suggest using the one that is in the App Store right now. I think it is Xcode 11.5
https://github.com/airbnb/lottie-ios/issues/1214

**Comment by framarini02** [comment]
I noticed one thing using the app. But aren't notifications supported?

**Comment by realpaliy** [comment]
Correct, this app does not support notifications.

**Comment by framarini02** [comment]
will you add them?

**Comment by realpaliy** [comment]
I'm not sure yet.
If you have any additional questions, email me. I'm closing this issue since the initial problem was resolved.
